#!/bin/bash
#SBATCH --output slurm.%N.%j.out     # STDOUT (%N: nodename, %j: job-ID)
#SBATCH --error slurm.%N.%j.err      # STDERR
#SBATCH --partition any              # partition (queue)
#SBATCH --ntasks 16                  # number of tasks/cores
#SBATCH --mem 110000                 # memory per node in MB
#SBATCH --time 6:00:00               # total runtime of job allocation

module load psi4/default
export PSI_SCRATCH=$TMPDIR

psi4 -n 16 245_T_conf2_freq.inp 245_T_conf2_freq.log
